#====================================================================
# Additional services for local development beyond Python and Node.js
#====================================================================
services:
  # Mongo Database
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db
      - ./backend/docker/mongo-users.js:/docker-entrypoint-initdb.d/mongo-users.js
      - ./backend/docker/create-indices.js:/docker-entrypoint-initdb.d/create-indices.js
    # Health check so that mongo-express doesn't try to connect when mongo
    # is not yet ready.
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  # Mongo Express database browser
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo_data: